meta:
  engine: 4.0.4
  name: lattice
  version: 2024.02
  author: sboysel
  url: https://github.com/sboysel/lattice

units:
  kx: U
  ky: U
  px: kx/2
  py: ky/2
  dx: -0.4kx
  dy: 0
  dr: 270
  vx: 0
  vy: py/2
  topy: ky
  usbx: 0
  usby: topy - 2.2

points:
  zones:
    matrix:
      anchor:
        shift: [5kx, -6ky]
      columns:
        outer:
        pinky:
        ring:
        middle:
        index:
        inner:
      rows:
        mods:
        bottom:
        home:
        top:
  key:
    spread: kx
    padding: ky

outlines:
  pcb:
    - what: polygon
      points:
        - ref: matrix_outer_top
          shift: [-px, topy]
        - ref: matrix_inner_top
          shift: [px, topy]
        - ref: matrix_inner_mods
          shift: [px, -py]
        - ref: matrix_outer_mods
          shift: [-px, -py]
      fillet: 3

pcbs:
  lattice_left:
    outlines:
      main:
        outline: pcb
        footprints:
    footprints:
      mx:
        what: placeholder
        where: true
        params:
          designator: MX
          value: MX_SW_HS
          side: B
      diode:
        what: placeholder
        where: true
        adjust:
          shift: [dx, dy]
          rotate: dr
        params:
          designator: D
          value: 1N4148W
          side: B
      j1: # usb c receptacle (host)
        what: placeholder
        where:
          ref: matrix_outer_top
        adjust:
          shift: [usbx, usby]
        params:
          designator: J
          value: USB_C_Receptacle
          side: B
      j2: # usb c receptacle (peripheral)
        what: placeholder
        where:
          ref: matrix_inner_top
        adjust:
          shift: [usbx, usby]
        params:
          designator: J
          value: USB_C_Receptacle
          side: B
      u1: # rp2040
        what: placeholder
        where:
          ref: matrix_middle_top
        adjust:
          shift: [0, 5py/4]
          rotate: 45
        params:
          designator: U
          value: RP2040
          side: B
      jlc_text:
        what: text 
        where:
          ref: matrix_outer_mods
          shift: [px, py]
        params:
          text: JLCJLCJLCJLC
          side: F
      side_text:
        what: text 
        where:
          ref: matrix_index_mods
          shift: [0, py]
        params:
          text: left
          side: F
      version_text:
        what: text 
        where:
          ref: matrix_inner_mods
          shift: [0, py]
        params:
          text: 'lattice v2024.02'
          side: F
