meta:
  engine: 4.0.4
  name: lattice
  version: 2024.02
  author: sboysel
  url: https://github.com/sboysel/lattice

units:
  kx: U
  ky: U
  px: kx/2
  py: ky/2
  dx: -0.4kx
  dy: 0
  dr: 270
  vx: 0
  vy: py/2
  topy: ky
  usbx: 0
  usby: topy - 2.2

points:
  zones:
    matrix:
      anchor:
        shift: [5kx, -6ky]
      columns:
        outer:
        pinky:
        ring:
        middle:
        index:
        inner:
      rows:
        mods:
        bottom:
        home:
        top:
  key:
    spread: kx
    padding: ky

outlines:
  pcb:
    - what: polygon
      points:
        - ref: matrix_outer_top
          shift: [-px, topy]
        - ref: matrix_inner_top
          shift: [px, topy]
        - ref: matrix_inner_mods
          shift: [px, -py]
        - ref: matrix_outer_mods
          shift: [-px, -py]
      fillet: 3

pcbs:
  lattice_left:
    outlines:
      main:
        outline: pcb
        footprints:
    footprints:
      # === Switches (Cherry MX hotswap)
      mx:
        what: placeholder
        where: true
        params:
          designator: MX
          value: MX_SW_HS
          side: B

      # === Diodes
      diode:
        what: placeholder
        where: true
        adjust:
          shift: [dx, dy]
          rotate: dr
        params:
          designator: D
          value: 1N4148W
          side: B

      # === USB C receptacle (host)
      j1: # usb c receptacle (host)
        what: placeholder
        where:
          ref: matrix_outer_top
        adjust:
          shift: [usbx, usby]
        params:
          designator: J
          value: USB_C_Receptacle
          side: B
      f1: # polyfuse 500mA
        what: placeholder
        where:
          ref: matrix_outer_top
        adjust:
          shift: [7, 3py/2]
          rotate: 90
        params:
          designator: F
          value: 500mA
          side: B
      r1: # 5k1
        what: placeholder
        where:
          ref: matrix_outer_top
        adjust:
          shift: [-7, py + 1]
          rotate: 180
        params:
          designator: R
          value: 5k1
          side: B
      r2: # 5k1
        what: placeholder
        where:
          ref: matrix_outer_top
        adjust:
          shift: [-7, py - 1]
          rotate: 180
        params:
          designator: R
          value: 5k1
          side: B

      # === USB C receptacle (peripheral)
      j2: 
        what: placeholder
        where:
          ref: matrix_inner_top
        adjust:
          shift: [usbx, usby]
        params:
          designator: J
          value: USB_C_Receptacle
          side: B
      
      # === RP2040
      u1:
        what: placeholder
        where:
          ref: matrix_middle_top
        adjust:
          shift: [0, 5py/4]
          rotate: (45+180)
        params:
          designator: U
          value: RP2040
          side: B
      r3: # 27R
        what: placeholder
        where:
          ref: matrix_middle_top
        adjust:
          shift: [8, 3py/2 + 2]
          rotate: 0
        params:
          designator: R
          value: 27R
          side: B
      r4: # 27R
        what: placeholder
        where:
          ref: matrix_middle_top
        adjust:
          shift: [8, 3py/2]
          rotate: 0
        params:
          designator: R
          value: 27R
          side: B
      r5: # 1k
        what: placeholder
        where:
          ref: matrix_middle_top
        adjust:
          shift: [8, 3py/2 - 2]
          rotate: 0
        params:
          designator: R
          value: 1k
          side: B

      
      # === U2
      u2: # W25Q128JVS (FLASH 128MB)
        what: placeholder
        where:
          ref: matrix_pinky_top
        adjust:
          shift: [-px/2, 3py/2]
          rotate: 270
        params:
          designator: U
          value: W25Q128JVS
          side: B
      c1:
        what: placeholder
        where:
          ref: matrix_pinky_top
        adjust:
          shift: [-px, 3py/2]
          rotate: 270
        params:
          designator: C
          value: 1uF
          side: B
      c2:
        what: placeholder
        where:
          ref: matrix_pinky_top
        adjust:
          shift: [0, 3py/2]
          rotate: 270
        params:
          designator: C
          value: 1uF
          side: B

      # === USBLC6-2SC6 (transient voltage suppressor)
      u3: 
        what: placeholder
        where:
          ref: matrix_pinky_top
        adjust:
          shift: [px/2, 3py/2]
          rotate: 270
        params:
          designator: U
          value: USBLC6-2SC6
          side: B
      
      # === XC6206PxxxMR (volatage regulator)
      # part number: XC6206
      u4:
        what: placeholder
        where:
          ref: matrix_index_top
        adjust:
          shift: [-px/3, 3py/2]
        params:
          designator: U
          value: XC6206PxxxMR
          side: B
      c3:
        what: placeholder
        where:
          ref: matrix_middle_top
        adjust:
          shift: [px, 7py/8]
          rotate: 90
        params:
          designator: C
          value: 100nF
          side: B
      r6:
        what: placeholder
        where:
          ref: matrix_index_top
        adjust:
          shift: [-px/2, py]
          rotate: 0
        params:
          designator: R
          value: 1k
          side: B
      
      # === Crystal Oscillator (Crystal_GND24_Small)   
      # 12MHz 3225 SMD 4 PIN
      # part number: C9002
      y1: # 
        what: placeholder
        where:
          ref: matrix_index_top
        adjust:
          shift: [px/2, 3py/2]
        params:
          designator: Y
          value: 12MHz
          side: B
      c4:
        what: placeholder
        where:
          ref: matrix_index_top
        adjust:
          shift: [px, 3py/2]
          rotate: 90
        params:
          designator: C
          value: 22pF
          side: B
      c5:
        what: placeholder
        where:
          ref: matrix_index_top
        adjust:
          shift: [px, 3py/2]
          rotate: 90
        params:
          designator: C
          value: 22pF
          side: B
      r7:
        what: placeholder
        where:
          ref: matrix_index_top
        adjust:
          shift: [px/2, py]
          rotate: 0
        params:
          designator: R
          value: 1k
          side: B

      # === buttons
      # Alps SKQG
      # part number: C318884
      sw1: # button: RESET
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [-px/2, 3py/2 + 1]
          rotate: 0
        params:
          designator: SW
          value: SW_Push
          side: B
      sw2: # button: BOOT
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [px/2, 3py/2 + 1]
          rotate: 0
        params:
          designator: SW
          value: SW_Push
          side: B

      # === breakout
      j3:
        what: placeholder
        where:
          ref: matrix_pinky_home
        adjust:
          shift: [5, py]
          rotate: 90
        params:
          designator: J
          value: Conn_01x05
          side: B  

      # === decoupling capcitors
      # +3V3
      c6:
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [5, py]
          rotate: 90
        params:
          designator: C
          value: 10uF
          side: B
      c7:
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [3, py]
          rotate: 90
        params:
          designator: C
          value: 1uF
          side: B
      c8:
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [1, py]
          rotate: 90
        params:
          designator: C
          value: 100nF
          side: B
      c9:
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [-1, py]
          rotate: 90
        params:
          designator: C
          value: 100nF
          side: B
      c10:
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [-3, py]
          rotate: 90
        params:
          designator: C
          value: 100nF
          side: B
      c11:
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [-5, py]
          rotate: 90
        params:
          designator: C
          value: 100nF
          side: B
      c12:
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [-1, py/2]
          rotate: 90
        params:
          designator: C
          value: 100nF
          side: B
      c13:
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [-3, py/2]
          rotate: 90
        params:
          designator: C
          value: 100nF
          side: B
      c14:
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [-5, py/2]
          rotate: 90
        params:
          designator: C
          value: 100nF
          side: B
      # +1V1
      c15:
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [5, py/2]
          rotate: 90
        params:
          designator: C
          value: 1uF
          side: B
      c16:
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [3, py/2]
          rotate: 90
        params:
          designator: C
          value: 100nF
          side: B
      c17:
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [1, py/2]
          rotate: 90
        params:
          designator: C
          value: 100nF
          side: B
      
      # === logos and text
      oshw: # make sure to uncheck "exclude from board" in schematic
        what: placeholder 
        where:
          ref: matrix_ring_mods
        adjust:
          shift: [px, py]
          rotate: 180
        params:
          designator: SYM
          value: Logo_Open_Hardware_Small
          side: B
      jlc_text:
        what: text 
        where:
          ref: matrix_outer_mods
          shift: [px, py]
        params:
          text: JLCJLCJLCJLC
          side: F
      side_text:
        what: text 
        where:
          ref: matrix_outer_mods
          shift: [px, py]
        params:
          text: left
          side: B
          justify: mirror
          knockout: true
          # face: "JetBrainsMono NF"
      version_text:
        what: text 
        where:
          ref: matrix_index_mods
          shift: [px, py]
        params:
          text: 'lattice v2024.02'
          side: B
          justify: mirror
          knockout: true
          # face: "JetBrainsMono NF"
