meta:
  engine: 4.0.4
  name: lattice
  version: 2024.02
  author: sboysel
  url: https://github.com/sboysel/lattice

units:
  kx: U
  ky: U
  px: kx/2
  py: ky/2
  dx: -0.4kx
  dy: py/2
  dr: 270
  vx: 0
  vy: py/2
  topy: ky
  usby: topy - 2

points:
  zones:
    matrix:
      anchor:
        shift: [5kx, -6ky]
      columns:
        outer:
        pinky:
        ring:
        middle:
        index:
        inner:
      rows:
        mods:
        bottom:
        home:
        top:
  key:
    spread: kx
    padding: ky

outlines:
  pcb:
    - what: polygon
      points:
        # NW
        - ref: matrix_outer_top
          shift: [-px, topy]
        # NE
        - ref: matrix_inner_top
          shift: [px, topy]
        # SE
        - ref: matrix_inner_mods
          shift: [px, -py]
        # SW
        - ref: matrix_outer_mods
          shift: [-px, -py]
      fillet: 3

pcbs:
  lattice_left:
    outlines:
      main:
        outline: pcb
        footprints:
    footprints:
      mx:
        what: placeholder
        where: true
        params:
          designator: MX
          value: MX_SW_HS
          side: B
      diode:
        what: placeholder
        where: true
        adjust:
          shift: [dx, dy]
          rotate: dr
        params:
          designator: D
          value: 1N4148W
          side: B
      
      # diodes_top:
      #   what: sod123_pad2_tht
      #   where:
      #     - /_top/
      #     - /_home/
      #   adjust:
      #     shift: [-px/2, -py]
      #     rotate: 0
      #   params:
      #     from: "{{colrow}}"
      #     to: "{{row_net}}"
      #     side: 'B'
      #     value: 'SOD-123 1N4148W'
      # diodes_mods:
      #   what: sod123_pad2_tht
      #   where:
      #     - /_mods/
      #   adjust:
      #     shift: [-px/2, py]
      #     rotate: 0
      #   params:
      #     from: "{{colrow}}"
      #     to: "{{row_net}}"
      #     side: 'B'
      #     value: 'SOD-123 1N4148W'       
      # CH552T:
      #   what: tssop20
      #   where:
      #     ref: matrix_middle_top
      #     shift: [px, py/2 + 0.5]
      #   adjust:
      #     rotate: 270
      #   params:
      #     side: B
      #     reference: U1
      #     value: CH552T
      #     P1: COL1
      #     P2: COL2
      #     P3: COL3
      #     P4: COL4
      #     P5: COL5
      #     P6: RST
      #     P7: ROW1
      #     P8: ROW2
      #     P9: ROW3
      #     P10: ROW4
      #     P11: ''
      #     P12: ''
      #     P13: ''
      #     P14: DP
      #     P15: DN
      #     P16: TX # output
      #     P17: RX # input
      #     P18: GND
      #     P19: VCC
      #     P20: V33
      # # Connectors
      # usb_host:
      #   what: usbc
      #   where:
      #     ref: matrix_outer_top
      #     shift: [0, usby]
      #   adjust:
      #     rotate: 180
      #   params:
      #     side: 'B'
      #     reference: 'J1'
      #     S1: ''
      #     S2: ''
      #     S3: ''
      #     S4: ''
      #     B1_A12: GND
      #     B4_A9: VCC
      #     A8: ''
      #     B8: ''
      #     A7: DN
      #     B7: DN
      #     A6: DP
      #     B6: DP
      #     A5: CC1 # 5.1k Ohm resistor -> GND
      #     B5: CC2 # 5.1k Ohm resistor -> GND
      #     A4_B9: VCC
      #     A1_B12: GND
      # usb_split:
      #   what: usbc
      #   where:
      #     ref: matrix_inner_top
      #     shift: [0, usby]
      #   adjust:
      #     rotate: 180    
      #   params:
      #     side: B
      #     reference: J2  
      #     S1: '' 
      #     S2: ''
      #     S3: ''
      #     S4: ''
      #     B1_A12: GND
      #     B4_A9: VCC
      #     A8: ''
      #     B8: ''
      #     A7: TX
      #     B7: TX
      #     A6: RX
      #     B6: RX
      #     A5: ''
      #     B5: ''
      #     A4_B9: VCC
      #     A1_B12: GND
      # # silkscreen text
      # jlc_text:
      #   what: text 
      #   where:
      #     ref: matrix_pinky_home
      #     shift: [px, py/2]
      #   params:
      #     text: 'JLCJLCJLCJLC'
      #     side: 'B'
      #     justify: 'mirror'
      # side_text:
      #   what: text 
      #   where:
      #     ref: matrix_middle_home
      #     shift: [0, py/2]
      #   params:
      #     text: 'left'
      #     side: 'B'
      #     justify: 'mirror'
      # version_text:
      #   what: text 
      #   where:
      #     ref: matrix_index_home
      #     shift: [px, py/2]
      #   params:
      #     text: 'moonfish v2024.01'
      #     side: 'B'
      #     justify: 'mirror'
