meta:
  engine: 4.0.4
  name: lattice
  version: 2024.02
  author: sboysel
  url: https://github.com/sboysel/lattice

units:
  kx: U
  ky: U
  px: kx/2
  py: ky/2
  dx: -0.4kx
  dy: 0
  dr: 270
  vx: 0
  vy: py/2
  topy: ky
  usbx: 0
  usby: topy - 2.2

points:
  zones:
    matrix:
      anchor:
        shift: [5kx, -6ky]
      columns:
        outer:
        pinky:
        ring:
        middle:
        index:
        inner:
      rows:
        mods:
        bottom:
        home:
        top:
  key:
    spread: kx
    padding: ky

outlines:
  pcb:
    - what: polygon
      points:
        - ref: matrix_outer_top
          shift: [-px, topy]
        - ref: matrix_inner_top
          shift: [px, topy]
        - ref: matrix_inner_mods
          shift: [px, -py]
        - ref: matrix_outer_mods
          shift: [-px, -py]
      fillet: 3

pcbs:
  lattice_left:
    outlines:
      main:
        outline: pcb
        footprints:
    footprints:
      mx:
        what: placeholder
        where: true
        params:
          designator: MX
          value: MX_SW_HS
          side: B
      diode:
        what: placeholder
        where: true
        adjust:
          shift: [dx, dy]
          rotate: dr
        params:
          designator: D
          value: 1N4148W
          side: B
      j1: # usb c receptacle (host)
        what: placeholder
        where:
          ref: matrix_outer_top
        adjust:
          shift: [usbx, usby]
        params:
          designator: J
          value: USB_C_Receptacle
          side: B
      j2: # usb c receptacle (peripheral)
        what: placeholder
        where:
          ref: matrix_inner_top
        adjust:
          shift: [usbx, usby]
        params:
          designator: J
          value: USB_C_Receptacle
          side: B
      u1: # rp2040
        what: placeholder
        where:
          ref: matrix_middle_top
        adjust:
          shift: [0, 5py/4]
          rotate: 45
        params:
          designator: U
          value: RP2040
          side: B
      u2: # W25Q128JVS (FLASH 128MB)
        what: placeholder
        where:
          ref: matrix_pinky_top
        adjust:
          shift: [0, 5py/4]
        params:
          designator: U
          value: W25Q128JVS
          side: B
      u3: # USBLC6-2SC6 (transient voltage suppressor)
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [0, 5py/4]
        params:
          designator: U
          value: USBLC6-2SC6
          side: B
      u4: # XC6206PxxxMR
        what: placeholder
        where:
          ref: matrix_index_top
        adjust:
          shift: [-px/2, 5py/4]
        params:
          designator: U
          value: XC6206PxxxMR
          side: B
      y1: # Crystal_GND24_Small (0603 SMD)
        what: placeholder
        where:
          ref: matrix_index_top
        adjust:
          shift: [px/2, 5py/4]
        params:
          designator: Y
          value: Crystal_GND24_Small
          side: B
      f1: # polyfuse 500mA
        what: placeholder
        where:
          ref: matrix_outer_top
        adjust:
          shift: [px, 5py/4]
          rotate: 90
        params:
          designator: F
          value: 500mA
          side: B
      r1: # 5k1
        what: placeholder
        where:
          ref: matrix_outer_top
        adjust:
          shift: [-7, py + 1]
          rotate: 180
        params:
          designator: R
          value: 5k1
          side: B
      r2: # 5k1
        what: placeholder
        where:
          ref: matrix_outer_top
        adjust:
          shift: [-7, py - 1]
          rotate: 180
        params:
          designator: R
          value: 5k1
          side: B
      oshw: # make sure to uncheck "exclude from board" in schematic
        what: placeholder 
        where:
          ref: matrix_ring_mods
        adjust:
          shift: [px, py]
          rotate: 180
        params:
          designator: SYM
          value: Logo_Open_Hardware_Small
          side: B
      jlc_text:
        what: text 
        where:
          ref: matrix_outer_mods
          shift: [px, py]
        params:
          text: JLCJLCJLCJLC
          side: F
      side_text:
        what: text 
        where:
          ref: matrix_outer_mods
          shift: [px, py]
        params:
          text: left
          side: B
          justify: mirror
          knockout: true
          face: "JetBrainsMono NF"
      version_text:
        what: text 
        where:
          ref: matrix_index_mods
          shift: [px, py]
        params:
          text: 'lattice v2024.02'
          side: B
          justify: mirror
          knockout: true
          face: "JetBrainsMono NF"
