meta:
  engine: 4.0.5
  name: lattice
  version: 2025.01
  author: sboysel
  url: https://github.com/sboysel/lattice

units:
  kx: 17 # cfx
  ky: 17
  px: kx/2
  py: ky/2
  dx: 0
  dy: 4.75
  dr: 180
  vx: 0
  vy: py/2
  topy: ky
  usbx: 0
  usby: topy - 2.25

points:
  zones:
    matrix:
      anchor:
        shift: [7kx, -8ky]
      columns:
        outer:
        pinky:
        ring:
        middle:
        index:
        inner:
      rows:
        mods:
        bottom:
        home:
        top:
  key:
    spread: kx
    padding: ky

outlines:
  pcb:
    - what: polygon
      points:
        - ref: matrix_outer_top
          shift: [-px, topy]
        - ref: matrix_inner_top
          shift: [px, topy]
        - ref: matrix_inner_mods
          shift: [px, -py]
        - ref: matrix_outer_mods
          shift: [-px, -py]
      fillet: 3

pcbs:
  lattice:
    outlines:
      main:
        outline: pcb
        footprints:
    footprints:
      # === Switches (Gateron Low Profile ks-27 / hotswap)
      choc:
        what: placeholder
        where: true
        adjust:
          rotate: 0
        params:
          designator: K
          value: SW_choc_v1_1u
          side: F

      # === Diodes
      diode:
        what: placeholder
        where: true
        adjust:
          shift: [dx, dy]
          rotate: dr
        params:
          designator: D
          value: 1N4148W
          side: F

      # === CH552T
      u1:
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [px, topy - 4.5]
          rotate: 90
        params:
          designator: U
          value: CH552T
          side: F
      c1: # 100n
        what: placeholder
        where:
          ref: matrix_middle_top
        adjust:
          shift: [0, topy - 2]
          rotate: 0
        params:
          designator: C
          value: 100n
          side: F
      c2: # 100n
        what: placeholder
        where:
          ref: matrix_middle_top
        adjust:
          shift: [0, topy - 4]
          rotate: 0
        params:
          designator: C
          value: 100n
          side: F


      # === USB C receptacle (left)
      j1:
        what: placeholder
        where:
          ref: matrix_outer_top
        adjust:
          shift: [usbx, usby]
          rotate: 180
        params:
          designator: J
          value: USB_C_Receptacle
          side: F
      f1: # polyfuse 500mA
        what: placeholder
        where:
          ref: matrix_outer_top
        adjust:
          shift: [px, topy - 2]
          rotate: 0
        params:
          designator: F
          value: 500mA
          side: F
      r1: # 5k1
        what: placeholder
        where:
          ref: matrix_outer_top
        adjust:
          shift: [px, topy - 4]
          rotate: 0
        params:
          designator: R
          value: 5k1
          side: F
      r2: # 5k1
        what: placeholder
        where:
          ref: matrix_outer_top
        adjust:
          shift: [px, topy - 6]
          rotate: 0
        params:
          designator: R
          value: 5k1
          side: F

      # === USBLC6-2SC6 (transient voltage suppressor)
      u2: # left 
        what: placeholder
        where:
          ref: matrix_pinky_top
        adjust:
          shift: [-2, topy - 4]
          rotate: 180
        params:
          designator: U
          value: USBLC6-2SC6
          side: F

      # === USB C receptacle (right)
      j2: 
        what: placeholder
        where:
          ref: matrix_inner_top
        adjust:
          shift: [usbx, usby]
          rotate: 180
        params:
          designator: J
          value: USB_C_Receptacle
          side: F
      f2: # polyfuse 500mA
        what: placeholder
        where:
          ref: matrix_inner_top
        adjust:
          shift: [-px, topy - 2]
          rotate: 180
        params:
          designator: F
          value: 500mA
          side: F
      r3: # 5k1
        what: placeholder
        where:
          ref: matrix_inner_top
        adjust:
          shift: [-px, topy - 4]
          rotate: 180
        params:
          designator: R
          value: 5k1
          side: F
      r4: # 5k1
        what: placeholder
        where:
          ref: matrix_inner_top
        adjust:
          shift: [-px, topy - 6]
          rotate: 180
        params:
          designator: R
          value: 5k1
          side: F
      
      # === USBLC6-2SC6 (transient voltage suppressor)
      u3: # right
        what: placeholder
        where:
          ref: matrix_index_top
        adjust:
          shift: [2, topy - 4]
          rotate: 0
        params:
          designator: U
          value: USBLC6-2SC6
          side: F

      # === boot button
      b1:
        what: placeholder
        where:
          ref: matrix_middle_top
        adjust:
          shift: [px, topy - 4]
          rotate: 0
        params:
          designator: B
          value: SW_SPST_SKQG
          side: F
      r5: # 10k
        what: placeholder
        where:
          ref: matrix_middle_top
        adjust:
          shift: [0, topy - 6]
          rotate: 180
        params:
          designator: R
          value: 10k
          side: F

      # === jumpers
      jp1:
        what: placeholder
        where:
          ref: matrix_pinky_top
        adjust:
          shift: [4, topy - 4]
          rotate: 270
        params:
          designator: JP
          value: SolderJumper_3_Open
          side: F
      jp2:
        what: placeholder
        where:
          ref: matrix_pinky_top
        adjust:
          shift: [6.5, topy - 4]
          rotate: 270
        params:
          designator: JP
          value: SolderJumper_3_Open
          side: F
      jp3:
        what: placeholder
        where:
          ref: matrix_pinky_top
        adjust:
          shift: [9, topy - 4]
          rotate: 270
        params:
          designator: JP
          value: SolderJumper_3_Open
          side: F
      jp4:
        what: placeholder
        where:
          ref: matrix_pinky_top
        adjust:
          shift: [11.5, topy - 4]
          rotate: 270
        params:
          designator: JP
          value: SolderJumper_3_Open
          side: F
      jp5:
        what: placeholder
        where:
          ref: matrix_pinky_top
        adjust:
          shift: [14, topy - 4]
          rotate: 270
        params:
          designator: JP
          value: SolderJumper_3_Open
          side: F
      jp6:
        what: placeholder
        where:
          ref: matrix_pinky_top
        adjust:
          shift: [16.5, topy - 4]
          rotate: 270
        params:
          designator: JP
          value: SolderJumper_3_Open
          side: F
      # TODO: add JumperLabels footprint
      jp_labels:
        what: placeholder
        where:
          ref: matrix_pinky_top
        adjust:
          shift: [10.25, topy - 4]
          rotate: 0
        params:
          designator: L
          value: SolderJumperLabel
          side: F

      # === logos and text
      oshw: # make sure to uncheck "exclude from board" in schematic
        what: placeholder 
        where:
          ref: matrix_index_mods
        adjust:
          shift: [px, py]
          rotate: 180
        params:
          designator: SYM
          value: Logo_Open_Hardware_Small
          side: B
      version_text:
        what: text 
        where:
          ref: matrix_outer_mods
          shift: [px, py]
        params:
          text: 'lattice v2025.01'
          side: B
          justify: mirror
      jlc_text:
        what: text 
        where:
          ref: matrix_outer_mods
          shift: [px, -py + 1]
        params:
          text: JLCJLCJLCJLC
          side: B
          justify: mirror
