meta:
  engine: 4.0.5
  name: lattice
  version: 2024.03
  author: sboysel
  url: https://github.com/sboysel/lattice

units:
  kx: U
  ky: U
  px: kx/2
  py: ky/2
  dx: -8.25
  dy: 0
  dr: 270
  vx: 0
  vy: py/2
  topy: py + ky/4
  usbx: 0
  usby: topy - 2.2

points:
  zones:
    matrix:
      anchor:
        shift: [5kx, -6ky]
      columns:
        outer:
        pinky:
        ring:
        middle:
        index:
        inner:
      rows:
        mods:
        bottom:
        home:
        top:
  key:
    spread: kx
    padding: ky

outlines:
  pcb:
    - what: polygon
      points:
        - ref: matrix_outer_top
          shift: [-px, topy]
        - ref: matrix_inner_top
          shift: [px, topy]
        - ref: matrix_inner_mods
          shift: [px, -py]
        - ref: matrix_outer_mods
          shift: [-px, -py]
      fillet: 3

pcbs:
  lattice:
    outlines:
      main:
        outline: pcb
        footprints:
    footprints:
      # === Switches (Gateron Low Profile ks-27 / hotswap)
      mx:
        what: placeholder
        where: true
        adjust:
          rotate: 0
        params:
          designator: MX
          value: MX_SW_HS
          side: B

      # === Diodes
      diode:
        what: placeholder
        where: true
        adjust:
          shift: [dx, dy]
          rotate: dr
        params:
          designator: D
          value: 1N4148W
          side: B

      # === USB C receptacle (left)
      j1:
        what: placeholder
        where:
          ref: matrix_outer_top
        adjust:
          shift: [usbx, usby]
        params:
          designator: J
          value: USB_C_Receptacle
          side: B
      f1: # polyfuse 500mA
        what: placeholder
        where:
          ref: matrix_outer_top
        adjust:
          shift: [px, py]
          rotate: 0
        params:
          designator: F
          value: 500mA
          side: B
      r1: # 5k1
        what: placeholder
        where:
          ref: matrix_outer_top
        adjust:
          shift: [px, py + 1.7]
          rotate: 0
        params:
          designator: R
          value: 5k1
          side: B
      r2: # 5k1
        what: placeholder
        where:
          ref: matrix_outer_top
        adjust:
          shift: [px, py + 3.4]
          rotate: 0
        params:
          designator: R
          value: 5k1
          side: B

      # === toggles
      sw1:
        what: placeholder
        where:
          ref: matrix_pinky_top
        adjust:
          shift: [0, py]
          rotate: 0
        params:
          designator: SW
          value: SW_Slide_DPDT
          side: B
      sw2:
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [px, py]
          rotate: 0
        params:
          designator: SW
          value: SW_Slide_DPDT
          side: B
      sw3:
        what: placeholder
        where:
          ref: matrix_index_top
        adjust:
          shift: [0, py]
          rotate: 0
        params:
          designator: SW
          value: SW_Slide_DPDT
          side: B

      # === buttons
      b1: # 
        what: placeholder
        where:
          ref: matrix_ring_home
        adjust:
          shift: [0, 7]
          rotate: 0
        params:
          designator: B
          value: SW_SPST
          side: B
      r3: # 330R
        what: placeholder
        where:
          ref: matrix_ring_home
        adjust:
          shift: [-7, 8.7]
          rotate: 180
        params:
          designator: R
          value: 330R
          side: B
      c1: # 100n
        what: placeholder
        where:
          ref: matrix_ring_home
        adjust:
          shift: [-7, 7]
          rotate: 0
        params:
          designator: C
          value: 100n
          side: B
      b2:
        what: placeholder
        where:
          ref: matrix_middle_home
        adjust:
          shift: [0, 7]
          rotate: 0
        params:
          designator: B
          value: SW_SPST
          side: B
      r4: # 10k
        what: placeholder
        where:
          ref: matrix_middle_home
        adjust:
          shift: [7, 7]
          rotate: 0
        params:
          designator: R
          value: 10k
          side: B

      # === CH552T
      u1:
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [-px/2, py]
          rotate: 0
        params:
          designator: U
          value: CH552T
          side: B
      c2: # 100n
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [1, 7.7]
          rotate: 0
        params:
          designator: C
          value: 100n
          side: B
      c3: # 100n
        what: placeholder
        where:
          ref: matrix_ring_top
        adjust:
          shift: [1, 6]
          rotate: 0
        params:
          designator: C
          value: 100n
          side: B

      # === USBLC6-2SC6 (transient voltage suppressor)
      u2: 
        what: placeholder
        where:
          ref: matrix_middle_top
        adjust:
          shift: [px/2, py]
          rotate: 90
        params:
          designator: U
          value: USBLC6-2SC6
          side: B

      # === USB C receptacle (right)
      j2: 
        what: placeholder
        where:
          ref: matrix_inner_top
        adjust:
          shift: [usbx, usby]
        params:
          designator: J
          value: USB_C_Receptacle
          side: B 
      f2: # polyfuse 500mA
        what: placeholder
        where:
          ref: matrix_inner_top
        adjust:
          shift: [-px, py]
          rotate: 0
        params:
          designator: F
          value: 500mA
          side: B
      r5: # 5k1
        what: placeholder
        where:
          ref: matrix_inner_top
        adjust:
          shift: [-px, py + 1.7]
          rotate: 0
        params:
          designator: R
          value: 5k1
          side: B
      r6: # 5k1
        what: placeholder
        where:
          ref: matrix_inner_top
        adjust:
          shift: [-px, py + 3.4]
          rotate: 0
        params:
          designator: R
          value: 5k1
          side: B
      
      # === logos and text
      version_text:
        what: text 
        where:
          ref: matrix_index_home
          shift: [px, py]
        params:
          text: 'lattice v2024.03'
          side: B
          justify: mirror
      oshw: # make sure to uncheck "exclude from board" in schematic
        what: placeholder 
        where:
          ref: matrix_index_bottom
        adjust:
          shift: [px, py]
          rotate: 180
        params:
          designator: SYM
          value: Logo_Open_Hardware_Small
          side: B
      jlc_text:
        what: text 
        where:
          ref: matrix_index_mods
          shift: [px, py]
        params:
          text: JLCJLCJLCJLC
          side: F
